### ISSUE TITLE
Field of type imagelist seems to contain taxonomy

### ISSUE THREAD

**Issue by madc** [xiaohutai/jsonapi#10]
This is my contenttype:

```
equipment:
    name: Things
    singular_name: Thing
    icon_many: fa:rocket
    icon_one: fa:rocket
    taxonomy: categories
    fields:
        name:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: name
        description:
            type: markdown
            label: Beschreibung
        images:
            type: imagelist
            label: Bilder (*.jpg)
            extensions: [ jpg ]
            upload: equipment/images
```

Here is the JSON object, thats coming back:

```
attributes: {
    description: "My description",
    images: [
        {
            "/categories/haushalt": "Haushalt",
            "/categories/werkzeuge": "Werkzeuge"
        }
    ],
    name: "Hammer",
    slug: "hammer",
    taxonomy: {
        categories: {
            "/categories/haushalt": "Haushalt",
            "/categories/werkzeuge": "Werkzeuge"
        }

    }
},
id: 1,
links: {..},
type: "equipment"
```
