### ISSUE TITLE
No URL in repeater images

### ISSUE THREAD

**Issue by iamajoe** [xiaohutai/jsonapi#44]
I've set a `contenttype` which has a simple `image` and a `repeater` of images:

```
pages:
    name: Pages
    singular_name: Page
    slug: pages
    singular_slug: page
    fields:
        title:
            type: text
        thumb:
            type: image
            attrib: [title, alt]
            extensions: [jpg]
        image:
            type: repeater
            limit: 8
            fields:
                repeatimage:
                    type: image
                    attrib: [title, alt]
                    extensions: [jpg]
    taxonomy: tags
    show_on_dashboard: true
    viewless: true
    default_status: publish
    sort: -datepublish
    searchable: false
    icon_many: fa:files-o
    icon_one: fa:file-o
```

When I request the `pages` list, `image` comes with an `url` (which is expected) but the `repeater` doesn't.

Here is the response:
```
{
    "thumb": {
        "file": "foo_thumb.jpg",
        "title": "...",
        "alt": "...",
        "url": "http://localhost/foo_thumb.jpg",
        "thumbnail": "http://localhost/400x300/foo_thumb.jpg"
    },
    "image": [
        {
            "repeatimage": {
                "file": "foo_1.jpg",
                "title": "Foo 1",
                "alt": "Foo 1"
            }
        },
        {
            "repeatimage": {
                "file": "foo_2.jpg",
                "title": "Foo 2",
                "alt": "Foo 2"
            }
        }
    ]
}
```
