### ISSUE TITLE
Notice: Undefined variable: fieldType

### ISSUE THREAD

**Issue by jackiboy** [xiaohutai/jsonapi#60]
Hi.
I am getting an error when I try fetch data from a specific content type.

ContextErrorException in FieldFactory.php line 94: 
Notice: Undefined variable: fieldType

```
                   }
                }
            } elseif ($data instanceof Carbon) {
                $type = new Date($field, $data, $config);
            } elseif (!$data instanceof LazyCollection) {
                if (in_array($fieldType, self::$fileTypes)) {
                    $type = new File($field, $data, $resourceManager, $config);
                    $type->setFieldType($fieldType);
                } else {
                    //We need to check if the label is an int. If it isn't then we'll use that for type (repeaters).
                    if (is_int($label)) {
```

this is my content type YML

```
employees:
    name: Employees
    singular_name: Employee
    fields:
        title:
            label: Persons Name
            type: text
            class: large
            group: content
        jobtitle:
            label: Job Title
            type: text
            variant: inline
            postfix: "<p>Employee job tile.</p>"
        image:
            label: Profile Image
            type: image
            upload: members
            postfix: "<p>Employee Profile Image.</p>"
        description:
            label: Employee Bio
            type: html
            height: 250px
            postfix: "<p>Employee Bio text.</p>"
        email:
            label: Email Address
            type: text
            variant: inline
            postfix: "<p>Employee Email Address (Optional).</p>"
        linkedin:
            label: Linkedin Profile
            type: text
            variant: inline
            postfix: "<p>Employee Linkedin Profile (Optional).</p>"
    taxonomy: [ employeeGroups ]
    record_template: employee.twig
    recordsperpage: 100
    default_status: publish
    description: '<p style="font-size: 1.5rem; line-height: 1.15em">Edit and create Employee bios. These will appear on the "Our Team Page".</p>'
    icon_many: "fa:users"
    icon_one: "fa:users"
```

and this is the settings in the JSON Extension config

```
contenttypes:
  employees:
  projects:
    where-clause:
        status: 'published'
    order: -datepublish
```
I have also set the debug level to `8181` but I can't seem to get it to display the data. The Projects content type fetches without errors.

Cheers,
Jack
