### ISSUE TITLE
Error when making slug field hidden

### ISSUE THREAD

**Issue by rainpoiss** [xiaohutai/jsonapi#62]
Uncaught Exception: ContextErrorException .

ContextErrorException in FieldFactory.php line 94: 

contenttype.yml:
```
 hidefield:
        type: hidden
        fields:
            slug:
                type: slug
                uses: title_et
```
