### ISSUE TITLE
Fields of type File are incorrectly rendered inside a repeating block

### ISSUE THREAD

**Issue by rogierkoppejan** [xiaohutai/jsonapi#88]
When rendering a `RepeatingFieldCollection`, fields of type `File` (image, audio, etc) have an incorrect key. More specifically, the key is set to the type of field (i.e. `image`), while it should be the _label_ (i.e. `my_field_name`). This not only results in unexpected key names, but also overwrites previous file fields in the same block because they all have the same key.

Example, given the following block:

```yaml
my_block:
    type: block
    fields:
        my_fieldset:
            fields:
                first_image:
                    type: image
                second_image:
                    type: image
```

This will be rendered as:

```json
{
  "my_block": [
    {
      "image": {
        "file": "images/filename.jpg",
        "url": "http://hostname.com/files/",
        "thumbnail": "http://hostname.com/thumbs/400x300/images/filename.jpg"
      },
      "_block": "my_fieldset"
    }
  ]
}
```
