### ISSUE TITLE
Uncaught Exception: InvalidFieldNameException

### ISSUE THREAD

**Issue by jamieburchell** [xiaohutai/jsonapi#90]
After updating a project I've inherited from Bolt 3.2.2 / jsonapi 3.0.6 to Bolt to 3.2.20 / jsonapi 3.3.0 I'm getting `InvalidFieldNameException` when hitting the json endpoint:

```
InvalidFieldNameException in AbstractMySQLDriver.php line 71: 
An exception occurred while executing 'SELECT COUNT(*) as total FROM bolt_gallery gallery LEFT JOIN bolt_relations incomingrelation ON gallery.id = incomingrelation.to_id AND incomingrelation.to_contenttype='gallery' WHERE _gallery.status = ? GROUP BY gallery.id' with params ["published"]:
```

I really have no idea where the underscore is coming from before "gallery" in this instance, which I presume is the cause of the error.

The `contenttypes` in `jsonapi.bolt.yml` are

```
contenttypes:
    casestudies:
        list-fields: [ title, location, slug ]
        allowed-fields: [ title, location, slug ]
        where-clause:
            status: 'published'
            showonmap: true
        order: -datepublish
    gallery:
        list-fields: [ name ]
        allowed-fields: [ name ]
        where-clause:
            status: 'published'
        order: -datepublish
```

If I remove the `where-clause`, I get the full list of gallery items. Similarly, for case studies I'm getting:

```
InvalidFieldNameException in AbstractMySQLDriver.php line 71: 
An exception occurred while executing 'SELECT COUNT(*) as total FROM bolt_casestudies casestudies LEFT JOIN bolt_relations services ON casestudies.id = services.from_id AND services.from_contenttype='casestudies' AND services.to_contenttype='services' LEFT JOIN bolt_relations incomingrelation ON casestudies.id = incomingrelation.to_id AND incomingrelation.to_contenttype='casestudies' LEFT JOIN bolt_taxonomy tags ON casestudies.id = tags.content_id AND tags.contenttype='casestudies' AND tags.taxonomytype='tags' WHERE _casestudies.showonmap = ? GROUP BY casestudies.id, casestudies.id, casestudies.id' with params ["1"]:
```

Seems to be the same underscore issue, but the multiple group by clauses look odd too. Other areas of the project where these items are fetched and displayed seem to be working fine. I tried removing the relationship declarations from the main content types, wondering if something was amiss there, to no avail. 

This is my last shot before I abandon all hope of coaxing this project in to an updated state ;)

Any pointers much appreciated.
